---
  - name: Install clickhouse
    hosts: clickhouse
    remote_user: lechuk
    roles:
     - role: clickhouse-role
  - name: Install Vector
    hosts: vector
    remote_user: lechuk
    roles:
     - role: vector-role
  - name: Install Nginx
    hosts: lighthouse
    remote_user: lechuk
    roles:
     - role: nginx-role
  - name: Install Lighthouse
    hosts: lighthouse
    remote_user: lechuk
    roles:
     - role: lighrhouse-role

