---
- name: NGINX | Install epel-release
  become: true
  ansible.builtin.yum:
    name: epel-release
    state: present
- name: NGINX | Install NGINX
  become: true
  ansible.builtin.yum:
    name: nginx
    state: present
- name: NGINX | Create Config
  become: true
  ansible.legacy.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    mode: o644
  notify: Start nginx
